title: RealtyLegal
email: marcoacg09@gmail.com
phone: 661-124-19-62
address: Avenida Jose Haroz Aguilar \#2005 -2 Fraccionamiento Villa Turística Playas de Rosarito
description: >- # this means to ignore newlines until "baseurl:"
  RealtyLegal promociona y vende bienes raíces, ofrecemos asesoría legal para cuidar tu inversión y otorgar la certeza jurídica patrimonial que necesitas. Promovemos la administración y venta de tus terrenos previo la mejor difusión
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: minima
plugins:
  - jekyll-feed

